name: .NET MAUI Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  Build_Android:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Build Android App
        run: |
          dotnet build TipCalculator/TipCalculator.sln -f net9.0-android
          
      - name: Run unit tests
        run: dotnet test TipCalculator.Tests/TipCalculator.Tests.csproj --no-build

  Build_iOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS App
        run: |
          dotnet build TipCalculator/TipCalculator.sln -f net9.0-ios
          
      - name: Run unit tests
        run: dotnet test TipCalculator.Tests/TipCalculator.Tests.csproj --no-build
        
  Build_MacCatalyst:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

  Build_Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Setup .NET v9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Build Windows App
        run: |
          dotnet build TipCalculator/TipCalculator.sln -f net9.0-windows10.0.19041.0
      
      - name: Run unit tests
        run: dotnet test TipCalculator.Tests/TipCalculator.Tests.csproj --no-build
