name: Run Unit Tests for TipCalculator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0 # Use the appropriate version
          
      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore TipCalculator/TipCalculator.sln

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build TipCalculator/TipCalculator.sln --no-restore --configuration Release

      # Step 5: Run tests
      - name: Run unit tests
        run: dotnet test TipCalculator.Tests/TipCalculator.Tests.csproj --no-build --configuration Release
