name: .NET MAUI Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
   run-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Setup .NET v9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui --skip-manifest-update

      - name: Restore NuGet Packages
        run: dotnet restore TipCalculator/TipCalculator.csproj
      
      - name: Run unit tests
        run: dotnet test TipCalculator.Tests/TipCalculator.Tests.csproj
